CREATE DATABASE IF NOT EXISTS wechat DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE wechat;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS companion;
DROP TABLE IF EXISTS dialog;

CREATE TABLE USER (
	account VARCHAR(255) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	age INT(11) NOT NULL,
	sex VARCHAR(255) NOT NULL,
	head VARCHAR(255) NOT NULL,
	address VARCHAR(255),
	label VARCHAR(255),
	phone VARCHAR(255) NOT NULL,
	background VARCHAR(255) NOT NULL,
	PRIMARY KEY(account)
);


CREATE TABLE companion (
	I_account VARCHAR(11) NOT NULL,
	Y_account VARCHAR(11) NOT NULL,
	remark VARCHAR(11),
	PRIMARY KEY(I_account, Y_account)
);

CREATE TABLE dialog (
	account VARCHAR(255) NOT NULL,
	PRIMARY KEY(account)
);

